### PR TITLE
General code cleanup & avoiding ConcurrentModificationException

### PR DESCRIPTION
**Pull request by phenomax**
Hey!
With this commits I improved the general code structure (e.g. by removing unnecessary code) and also replaced the permission`s HashMaps with ConcurrentHashMaps.

So when editing permission attachments asychronously, we should not get any ConcurrentModificationExceptions anymore.

Greez

### CODE REVIEW

**Comment by Black-Hole** [comment]
This repository isn't used anymore. Have a look at https://hub.spigotmc.org/

**Comment by Puremin0rez** [comment]
^

**Comment by phenomax** [comment]
My bad. Being no pull for a year, I could have thought about that :)

**Comment by DanielRamosAcosta** [comment]
I recommend to update the readme to make this clear.

**Pull request closed without merging**
