### PR TITLE
Fix tab completion

### PR DESCRIPTION
**Pull request by ams2990**
`/plugins` and `/reload` are returning the player list in tab completion when they should be returning nothing, and `/tell` and `/testfor` return the player list for parameters beyond the first.

### CODE REVIEW

**Comment by md-5** [comment]
return ImmutableList.of();

Don't bother with validation checks unless you use the vars

**Comment by ams2990** [comment]
I'm confused -- I do return ImmutableList.of(). Unless you're talking about when I return the implementation in the superclass? I'm happy to change anything you want changed, but the format of these is identical to the ones in other Bukkit commands. Would you like me to change those, too?

**Comment by md-5** [comment]
Your code:

```
+    @Override

+    public List<String> tabComplete(CommandSender sender, String alias, String[] args) throws IllegalArgumentException {

+        Validate.notNull(sender, "Sender cannot be null");

+        Validate.notNull(args, "Arguments cannot be null");

+        Validate.notNull(alias, "Alias cannot be null");

+

+        return ImmutableList.of();

+    }
```

How I want it:

```
+    @Override

+    public List<String> tabComplete(CommandSender sender, String alias, String[] args) throws IllegalArgumentException {
+        return ImmutableList.of();

+    }
```

**Comment by ams2990** [comment]
Sure. Should I eliminate the unnecessary checks on other commands too?

**Comment by md-5** [comment]
Yeah all the commands which you have added return ImmutableList.of()

**Comment by ams2990** [comment]
Sorry, what I meant by that was, should I change Bukkit commands that already have `tabComplete` methods with unnecessary checks in them?

**Comment by md-5** [comment]
You added a bunch of validation which we do not need: http://files.md-5.net/s/3ia7.png

Please remove it

**Comment by ams2990** [comment]
We don't seem to be communicating very well :)

I know I need to remove the extra lines from my commit. I will do so. There are many other Bukkit commands that I didn't touch because they already have `tabComplete` methods on them. They have the extra validation that you are objecting to. Should I remove the validation from those files as well?

**Comment by md-5** [comment]
No, only remove the lines YOU added

**Comment by ams2990** [comment]
Done.

**Comment by md-5** [comment]
Pulled manually

**Pull request closed without merging**
