### PR TITLE
Add ReadMe.md in enhanced zeEnglish

### PR DESCRIPTION
**Pull request by MyPictures**
For the new fancy ze folks we should also provide some better language.
Ze Better!

### CODE REVIEW

**Comment by ghost** [comment]
0/10

**Comment by SuperSpyTX** [comment]
0/10, no Hcherndon love stickers D:

**Comment by MyPictures** [comment]
0 errors out of 10? I know.

**Comment by SuperSpyTX** [comment]
no, that's a rating, u dum arse

**Comment by MyPictures** [comment]
A rating out of errors?

**Comment by SuperSpyTX** [comment]
Rating overall

**Comment by MyPictures** [comment]
10/10

**Pull request closed without merging**
